# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-27 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TieZi',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('user', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=256)),
            ],
            options={
                'db_table': '\u5e16\u5b50\u8868',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('icon', models.ImageField(upload_to='icons')),
                ('sex', models.CharField(max_length=16)),
            ],
            options={
                'db_table': '\u7528\u6237\u8868',
            },
        ),
    ]
